os: linux
matrix:
  include:
    - os: osx
    - dist: trusty
      sudo: required
  exclude:
    - os: linux

env:
- PYENV_PYTHON_VERSION=3.5.2

before_install:
- ci/travis/before_install.sh
install:
- ci/travis/build.sh
script:
- ci/travis/test.sh
after_success:
- ci/travis/after_success.sh
before_deploy:
- ci/travis/before_deploy.sh

deploy:
  - provider: releases
    api_key:
      secure: MUdvTDBeCxO9d/EpzIhr+QYra/KxgYkXX6177SjqWCWDqw9xB3fwSUj8I9ht9DGtwVdadtveumtvLw3pbtVIR0GtIPC9pyvtNz4j6T4Ei3TSE6+StXdMK4NnInvPeTRlobGL+9sZt9MwheJwZ8YGewhBcR0F5UzVfxWeSSrxmyk=
    file:
      - sakia-${TRAVIS_OS_NAME}.zip
    skip_cleanup: true
    on:
      tags: true
      condition: ${TRAVIS_OS_NAME} = osx
  - provider: releases
    api_key:
      secure: MUdvTDBeCxO9d/EpzIhr+QYra/KxgYkXX6177SjqWCWDqw9xB3fwSUj8I9ht9DGtwVdadtveumtvLw3pbtVIR0GtIPC9pyvtNz4j6T4Ei3TSE6+StXdMK4NnInvPeTRlobGL+9sZt9MwheJwZ8YGewhBcR0F5UzVfxWeSSrxmyk=
    file:
      - sakia-${TRAVIS_OS_NAME}.deb
      - sakia-${TRAVIS_OS_NAME}.zip
    skip_cleanup: true
    on:
      tags: true
      condition: ${TRAVIS_OS_NAME} = linux
